# This workflow will install build my website and host 

name: CI_Deploiement

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installing dependencies
      run: |
        npm install
    
    - name: Building site
      run: |        
        npm run build
        
    - name: Install SSH Client 🔑
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        BRANCH: master
        FOLDER: dist
